apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprodb
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
      - name: vprodb
        image: sriuday19/vprodb
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: vprodb-port
          containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            value: accounts
        volumeMount:
          mountPath: /var/lib/mysql
          name: db-data
      volumes:
        - name: db-data
          awsElasticBlockStore:
            volumeID: 
            fsType: ext4
      nodeSelector:
        zone: us-east-1a  
      
      initContainer:
      - name: busybox
        image: busybox:latest
        command: ['rm', '-rf', '/var/lib/mysql/lost+found']
        volumeMount:
          mountPath: /var/lib/mysql
          name: db-data
