apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-rmq  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprormq

  template:
    metadata:
      labels:
        app: vprormq

    spec:
      containers:
      - name: vprormq
        image: rabbitmq
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: vprormq-port
          containerPort: 15672
        env:
         - name: RABBITMQ_DEFAULT_PASS
           valueFrom:
             secretKeyRef:
               name: app-secret
               key: RABBITMQ_DEFAULT_PASS
         - name: RABBITMQ_DEFAULT_USER
           value: "test"
